<?xml version="1.0"?>
<!--
Block on top of the iRobot Create 2
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find ca_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/camera_sensor.xacro"/>

  <xacro:macro name="roomblock" params="name:=roomblock parent:=base_link visualize:=false *origin">

    <xacro:property name="parent_link" value="${parent}"/>
    <xacro:property name="link_name"   value="${name}_link"/>

    <xacro:property name="mass"        value="0.1"/>
    <xacro:property name="size_x"      value="0.1"/>
    <xacro:property name="size_y"      value="0.1"/>
    <xacro:property name="size_z"      value="0.07"/>

    <joint name="block_joint" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent_link}"/>
      <child link="${link_name}" />
    </joint>

    <link name="${link_name}">
      <visual>
        <geometry>
  	       <mesh filename="package://ca_description/meshes/block.dae"/>
        </geometry>
        <material name="Grey" />
      </visual>
      <xacro:inertial_cuboid_with_pose mass="${mass}"
                                       x_length="${size_x}"
                                       y_length="${size_y}"
                                       z_length="${size_z}">
        <origin xyz="0 0 ${size_z/2}"/>
      </xacro:inertial_cuboid_with_pose>
    </link>

    <gazebo reference="${link_name}">
      <material>Gazebo/Grey</material>
    </gazebo>

    <xacro:include filename="$(find ca_description)/urdf/sensors/lasers/astra.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/lasers/kinect.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/lasers/realsense.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/lasers/rplidar.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/lasers/xtion_pro.xacro"/>

    <xacro:property name="laser" default="$(arg laser)"/>

    <!-- TODO: Implement this in a dictionary (along with include file) -->
    <xacro:if value="${laser == 'astra'}">
      <xacro:orbbec_astra>
        <origin xyz="0 0 0.2"/>
      </xacro:orbbec_astra>
    </xacro:if>
    <xacro:if value="${laser == 'kinect'}">
      <xacro:kinect>
        <origin xyz="0.025 -0.01 0.22"/>
      </xacro:kinect>
    </xacro:if>
    <xacro:if value="${laser == 'rplidar'}">
      <xacro:rplidar_a2 parent="${link_name}" visualize="${visualize}">
        <origin xyz="0 0 0.1"/>
      </xacro:rplidar_a2>
    </xacro:if>
    <xacro:if value="${laser == 'r200'}">
      <xacro:realsense_r200>
        <origin xyz="0 0 0.182"/>
      </xacro:realsense_r200>
    </xacro:if>
    <xacro:if value="${laser == 'xtion_pro'}">
      <xacro:asus_xtion_pro>
        <origin xyz="0.015 0.018 0.191"/>
      </xacro:asus_xtion_pro>
    </xacro:if>

    <!-- TODO (eborghi): ADD CAMERA CAD? REMOVE CAMERA/USE ANOTHER ONE? -->
    <xacro:camera_sensor name="raspicam" parent="${link_name}"/>

  </xacro:macro>

</robot>
