<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ca_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_base_gazebo.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_caster_wheel.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/create_wheel.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/imu_sensor.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/wall_sensor.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/cliff_sensors.xacro"/>
  <xacro:include filename="$(find ca_description)/urdf/sensors/omni_sensor.xacro"/>

  <xacro:macro name="create_base" params="wheel_separation wheel_radius wheel_width base_diameter *mesh">

    <xacro:property name="base_link_offset_z" value="0.0308"/>
    <xacro:property name="base_offset_z" value="0.017"/>
    <xacro:property name="base_height" value="0.0611632"/>
    <xacro:property name="base_mass" value="2"/>

    <xacro:arg name="visualize" default="false"/>

    <!-- The root link base_footprint has an inertia specified in the URDF,
         but KDL does not support a root link with an inertia.
         As a workaround, you can add an extra dummy link to your URDF. -->
    <!-- <joint name="fixed_joint" type="fixed">
      <parent link="dummy_link"/>
      <child link="base_footprint"/>
    </joint>
    <link name="dummy_link"/> -->

    <link name="base_footprint">
      <xacro:dummy_inertia/>
    </link>

    <joint name="base_footprint_joint" type="continuous">
      <origin xyz="0 0 ${base_offset_z}"/>
      <parent link="base_footprint" />
      <child link="base_link" />
      <axis xyz="1 0 0"/>
    </joint>

    <link name="base_link">
      <xacro:inertial_cylinder mass="${base_mass}" radius="${base_diameter/2}" length="${base_height}"/>

      <visual>
        <origin xyz=" 0 0 ${base_link_offset_z}"/>
        <geometry>
          <xacro:insert_block name="mesh" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${base_link_offset_z}"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_diameter/2}" />
        </geometry>
      </collision>
    </link>

    <xacro:wall_sensor>
      <origin xyz="0.09 -0.12 0.042" rpy="0 0 -1"/>
    </xacro:wall_sensor>

    <xacro:cliff_sensor name="side_left_cliff_sensor">
      <origin xyz="0.07 0.14 0.01" rpy="0 ${pi/2 - 0.09} 0" />
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="side_right_cliff_sensor">
      <origin xyz="0.07 -0.14 0.01" rpy="0 ${pi/2 - 0.09} 0" />
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="front_left_cliff_sensor">
      <origin xyz="0.15 0.04 0.01" rpy="0 ${pi/2 - 0.09} 0" />
    </xacro:cliff_sensor>

    <xacro:cliff_sensor name="front_right_cliff_sensor">
      <origin xyz="0.15 -0.04 0.01" rpy="0 ${pi/2 - 0.09} 0" />
    </xacro:cliff_sensor>

    <xacro:imu_sensor name="imu">
      <origin xyz="0 -0.04 0.13"/>
    </xacro:imu_sensor>

    <xacro:omni_sensor diameter="0.1">
      <origin xyz="0.145 0 ${base_link_offset_z}"/>
    </xacro:omni_sensor>

    <xacro:wheel name="wheel_left" radius="${wheel_radius}" width="${wheel_width}">
      <origin xyz="0 ${wheel_separation/2} 0.015" rpy="0 ${pi/2} ${pi/2}"/>
    </xacro:wheel>
    <xacro:wheel name="wheel_right" radius="${wheel_radius}" width="${wheel_width}">
      <origin xyz="0 ${-wheel_separation/2} 0.015" rpy="0 ${pi/2} ${pi/2}"/>
    </xacro:wheel>
    <xacro:caster_wheel>
      <origin xyz="0.13 0 0"/>
    </xacro:caster_wheel>

    <!-- Simulation sensors -->
    <xacro:sim_create_base/>
  </xacro:macro>
</robot>
